import "@/styles/globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";


import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import Script from "next/script";

export const metadata: Metadata = {
  title: "Edueme Research Lab",
  description: "Generated by Intern's Team",
  icons: [{ rel: "icon", url: "/e_logo.png" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <head>
        {/* Feather Icons Script */}
        <Script
          src="https://cdn.jsdelivr.net/npm/feather-icons/dist/feather.min.js"
          strategy="afterInteractive" // Ensures the script is loaded after the page loads
        />
      </head>
      <body>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
